module.exports = {
  roots: ['<rootDir>/src/__tests__'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  testRegex: '/__tests__/.*\\.(ts|js)$',
  testEnvironment: 'node',
  moduleFileExtensions: ['ts', 'js', 'json', 'node'],
  modulePathIgnorePatterns: ['utils.ts', 'setup.ts', 'coverage/'],
  coverageDirectory: 'src/__tests__/coverage/',
  collectCoverage: true,
  collectCoverageFrom: [
    'src/db/models/**',
    '!src/db/models/ActivityLogs.ts',
    '!src/db/models/definitions/**',
    'src/data/resolvers/mutations/**',
    '!src/data/resolvers/mutations/robot.ts',
    'src/data/resolvers/**',
    '!src/data/resolvers/customScalars.ts',
    '!src/data/resolvers/queries/insights.ts',
    '!src/data/resolvers/queries/robot.ts',
    '!src/data/resolvers/queries/logs.ts',
    '!src/index.ts',
    '!src/db/factories.ts',
    '!src/db/connection.ts',
    '!src/data/schema/**',
    '!src/db/models/definitions/**',
    '!src/data/resolvers/subscriptions/**',
    '!src/data/index.ts',
    '!src/data/utils.ts',
    '!src/workers/utils.ts',
  ],
  globals: {
    'ts-jest': {
      tsConfigFile: 'tsconfig.json',
    },
  },
};
